---
title: "Data Import"
output: github_document
---

# Section 1

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import a dataset.

read_csv better than 
```{r}
litters_df = 
    read_csv("./data_import_examples/FAS_litters.csv")
```
```{r}
names(litters_df)
```
Update the names in 'litters_df'
```{r}
litters_df = 
    janitor::clean_names(litters_df)
```
```{r}
litters_df
```

```{r}
skimr::skim(litters_df)

```
```{r}
litters_df = 
    read_csv(file = "./data_import_examples/FAS_litters.csv",
        na = c(".", "NA", ""),
    col_types = cols(
      Group = col_factor()
    )
)
```


```{r}
pups_df = 
    read_csv("./data_import_examples/FAS_pups.csv",
             skip = 3,
               na = c(".", "NA", "")
            )

litters_df = 
    janitor::clean_names(pups_df)

skimr::skim(pups_df)

```

```{r}
mlb_df = 
  read_excel ("./data_import_examples/mlb11.xlsx")
```

```{r}
fotr_df = 
    read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

```{r}
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)
```
